# Default values for mongo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
persistentVolumeClaim: matsdata
rootUrl: https://rancher.localhost
userId: ""
mongoUser: "matsadmin"
mongoPwd: "matsAdmin0"
image:
  repository: matsapps/development
  tag: nightly
  pullPolicy: IfNotPresent

