apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: {{ .Values.userId }}
    field.cattle.io/publicEndpoints: '[{"protocol":"TCP","serviceName":"{{ .Release.Namespace }}:mongo-nodeport","allNodes":true}]'
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-{{ .Release.Namespace }}-mongo
  name: mongo
  namespace: {{ .Release.Namespace }}
  selfLink: /apis/apps/v1/namespaces/{{ .Release.Namespace }}/deployments/mongo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-{{ .Release.Namespace }}-mongo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":27017,"dnsName":"mongo-nodeport","kind":"NodePort","name":"27017tcp01","protocol":"TCP"}]]'
      labels:
        workload.user.cattle.io/workloadselector: deployment-{{ .Release.Namespace }}-mongo
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: {{ .Values.adminMongoPassword }}
        - name: MONGO_INITDB_ROOT_USERNAME
          value: {{ .Values.adminMongoUser }}
        - name: MONGO_INITDB_DATABASE
          value: "admin"
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        name: mongo
        ports:
          - containerPort: 27017
            name: 27017tcp01
            protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
          - mountPath: /data/db
            name: data
            subPath: {{ .Values.persistentVolumeClaim }}/dev/mongodata
          - name: mongo-init
            mountPath: /docker-entrypoint-initdb.d
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolumeClaim }}
        - name: mongo-init
          configMap:
            name: mongo-init
