apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: {{ .Values.userId }}
    field.cattle.io/publicEndpoints: '[{"addresses":[""],"port":80,"protocol":"HTTP","serviceName":"{{ .Release.Namespace }}:home","ingressName":"{{ .Release.Namespace }}:matsapps-{{ .Release.Namespace }}","hostname":"{{ .Values.rootUrl }}","path":"/{{ .Release.Namespace }}/home","allNodes":false},{""protocol":"TCP","serviceName":"{{ .Release.Namespace }}:home-nodeport","allNodes":true}]'
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: "deployment-{{ .Release.Namespace }}-home"
  name: home
  selfLink: "/apis/apps/v1/namespaces/{{ .Release.Namespace }}/deployments/home"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: "deployment-{{ .Release.Namespace }}-home"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":80,"dnsName":"home-nodeport","kind":"NodePort","name":"80tcp01","protocol":"TCP"}]]'
      labels:
        workload.user.cattle.io/workloadselector: "deployment-{{ .Release.Namespace }}-home"
    spec:
      containers:
        - env:
            - name: MONOG_URL
              #MONGO_URL on our old nginx deployments ... mongodb://localhost:27017/met-surface - I think localhost needs to be mongo for the cluster address
              #mongodb://matsUser:mu-2019@mongo:27017/aircraft?authSource=admin
              value: "mongodb://{{ .Values.matsMongoUser }}:{{ .Values.matsMongoPassword }}@mongo:27017/home?authSource=admin"
            - name: DEPLOYMENT_ENVIRONMENT
              {{- if eq .Release.Namespace "matsdev" }}
              value: "development"
              {{- else if eq .Release.Namespace "matspreint" }}
              value: "integration"
              {{- else if eq .Release.Namespace "matsint" }}
              value: "production"
              {{- else if eq .Release.Namespace "matsprod" }}
              value: "production"
              {{- end }}
            - name: GROUP_ORDER
              value: Upper Air,Ceiling and Visibility,Surface,Precipitation,Radar,METexpress
            - name: ROOT_URL
              value: "{{ .Values.rootUrl }}/{{ .Release.Namespace }}/home"
          image: "{{ .Values.image.repository }}:mats-home-{{ .Values.image.tag }}"
          imagePullPolicy: Always
          name: home
          ports:
            - containerPort: 80
              name: 80tcp01
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: /usr/app/settings
              name: settings
              subPath: "{{ .Release.Namespace }}/settings"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: settings
          persistentVolumeClaim:
            claimName: matsdata
